services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    healthcheck:
      test: 'curl --silent localhost:8000'
      interval: 2s
      retries: 15
      timeout: 1s

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

volumes:
  dynamodb-data: {}
